# k8s/backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-backend
spec:
  selector:
    matchLabels:
      app: quiz-backend
  template:
    metadata:
      labels:
        app: quiz-backend
    spec:
      containers:
      - name: backend
        image: your-backend-image:latest
        env:
          - name: DATABASE_URL
            value: "mysql+pymysql://dev:devpass@quiz-mysql:3306/quizdb"
        ports:
          - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-backend
spec:
  type: ClusterIP
  selector:
    app: quiz-backend
  ports:
    - port: 5001
