# k8s/mysql.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: quiz-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-mysql
spec:
  selector:
    matchLabels:
      app: quiz-mysql
  template:
    metadata:
      labels:
        app: quiz-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: rootpass
          - name: MYSQL_DATABASE
            value: quizdb
          - name: MYSQL_USER
            value: dev
          - name: MYSQL_PASSWORD
            value: devpass
        ports:
          - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
