# k8s/seed-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: seed-db
spec:
  template:
    spec:
      containers:
      - name: seed
        image: your-backend-image:latest
        command: ["python", "seed_db.py"]
        env:
          - name: DATABASE_URL
            value: "mysql+pymysql://dev:devpass@quiz-mysql:3306/quizdb"
      restartPolicy: OnFailure
